name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chanwit/dev-demo:${{ env.RELEASE_VERSION }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}    
    - name: Push
      run: docker push chanwit/dev-demo:${{ env.RELEASE_VERSION }}
